config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user, ->(user) { user.owner? } do
    get 'owner', to: 'owner#dashboard'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :restaurants do
    resources :queuers, only: [ :new, :create, :edit, :update ]

    resources :reviews, only: [ :new, :create, :index ]
  end

  resources :queuers do
    resources :queuers, only: [ :show, :index, :destroy, :update ]
    member do
      patch :change_status
      delete :remove_queuer
      delete :quick_remove
      post :notify
    end
  end
end

app/models/queuer.rb
class Queuer < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  STATUS = ['queuing', 'dining', 'completed']
  validates :reservation_name, presence: true
  validates :size, presence: true, numericality: { only_integer: true }

  # after_create :reminder

  # Notify our queuer X minutes before their
  def reminder(time = Time.now)
    return unless user.phone.present?
    @twilio_number = ENV['TWILIO_NUMBER']
    account_sid = ENV['TWILIO_ACCOUNT_SID']
    @client = Twilio::REST::Client.new account_sid, ENV['TWILIO_AUTH_TOKEN']
    time_str = time.localtime.strftime("%I:%M%p on %b. %d, %Y")
    body = "Hi #{reservation_name}. Just a reminder that your turn is coming up at #{time_str}."
    message = @client.messages.create(
      :from => @twilio_number,
      :to => user.phone,
      :body => body
    )
  end

  def when_to_run
    # wait time is should be in minutes
    wait_time = wait_time.minutes
    turn_time = Time.now + wait_time
    turn_time - 15.minutes
  end

  #handle_asynchronously :reminder, :run_at => Proc.new { |i| i.when_to_run }

  def position
    queuers = self.restaurant.queuers.where(status: "queuing")
    queuers = queuers.sort_by { |queue| queue.created_at }
    index = queuers.find_index(self) + 1
    return index
  end

  def people
    queuers = self.restaurant.queuers.where(status: "queuing")
    queuers = queuers.sort_by { |queue| queue.created_at }
    queuers = queuers.take(position)
    # <!-- number of people waiting in the queue -->
    number_of_people = 0
    queuers.each do |group|
      number_of_people += group.size
    end
    return number_of_people
  end

  def people_ahead_in_queue
    people_ahead = people - self.size
    return people_ahead
  end

  def wait_time
    self.restaurant.time_per_person * people_ahead_in_queue
  end

  def estimated
    time = Time.zone.now  + (wait_time * 60)
    return time.strftime("%I:%M %p")
  end

end

app/controllers/queuers_controller.rb
class QueuersController < ApplicationController
  include ActionView::RecordIdentifier # adds `dom_id`
  # before_action :wait_time

  def show
    @queuer = Queuer.find(params[:id])
    restaurant_id = @queuer.restaurant_id
    @restaurant = Restaurant.find(restaurant_id)
    # <!-- Queue information -->
    @queuers = Queuer.where(restaurant_id: @restaurant, status: "queuing")
    @queuers = @queuers.sort_by { |queue| queue.created_at }
    @position = @queuers.find_index(@queuer) + 1
    # <!-- number of people waiting in the queue -->
    @number_of_people = 0
    @queuers.each do |group|
      @number_of_people += group.size
    end
    # @restaurant.total_wait_time = wait_time
  end

  def index
    @restaurant = Restaurant.where(user_id: current_user.id)
    # <!-- Active Queuers -->
    @queuers = Queuer.where(restaurant_id: @restaurant, status: "queuing")
    @queuers = @queuers.order(created_at: :asc)
    @number_of_queuers = @queuers.size
    @number_of_queuers = 0
    @queuers.each do |group|
      @number_of_queuers += group.size
    end
    # <!-- Active Diners -->
    @dining_queuers = Queuer.where(restaurant_id: @restaurant, status: "dining")
    @diners = @dining_queuers.size
    @number_of_diners = 0
    @dining_queuers.each do |group|
      @number_of_diners += group.size
    end

    @all_queuers = @queuers + @dining_queuers
    @all_queuers = @queuers.order(created_at: :asc)
    # <!-- Total Queuers -->
    @total_queuers = Queuer.where(restaurant_id: @restaurant)
    @total_queuers = @total_queuers.order(created_at: :asc)
    # <!-- Number of active customers -->
    @number_of_people = 0
    @queuers.each do |group|
      @number_of_people += group.size
    end
  end

  def new
    @queuer = Queuer.new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @username = current_user.email.split("@")[0]
  end

  def create
    @user_id = current_user.id
    @queuer = Queuer.new(queuer_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @queuer.restaurant = @restaurant
    @queuer.user_id = @user_id
    @queuer.status = "queuing"
    if @queuer.save
      QueuerMailer.with(queuer: @queuer).new_queuer(@queuer).deliver_later
      redirect_to queuer_path(@queuer)
    else
      render :new
    end
  end

  def update
    @queuer = Queuer.find(params[:id])
    @queuer.update(queuer_params)
  end

  def change_status
    @queuer = Queuer.find(params[:id])
    @queuer.update(status: params[:status])
    if params[:status] == "completed"
      redirect_to queuers_path, notice: "Status updated to #{@queuer.status}"
    else
      redirect_to queuers_path(anchor: dom_id(@queuer)), notice: "Status updated to #{@queuer.status}"
    end
  end

  def destroy
    @queuer = Queuer.find(params[:id])
    @restaurant = @queuer.restaurant
    @queuer.destroy
    redirect_to restaurant_path(@restaurant)
  end

  def remove_queuer
    @queuer = Queuer.find(params[:id])
    @queuer.destroy
    redirect_to queuers_path, notice: "Group Was Removed"
  end

  def quick_remove
    @queuer = Queuer.find(params[:id])
    @queuer.destroy
    redirect_to owner_path, notice: "Group Was Removed"
  end

  def notify
    @queuer = Queuer.find(params[:id])
    @queuer.reminder
    redirect_to request.referrer, notice: "Notification sent!"
  end

  private

    def queuer_params
      params.require(:queuer).permit(:size, :status, :reservation_name)
    end
end

app/views/queuers/_active.html.erb
</div>

<div class="container p-2">
    <!-- Active Queue -->
    <div class="queuers-tableheaders">
      <h2>Queue</h2>
      <h3><%= @queuers.size %> groups waiting (<%= @number_of_queuers %> queuers)</h3>
    </div>
</div>

    <div id="queuers">
      <% @queuers.each_with_index do | queue, index | %>
      <% if queue.status == "queuing" %>
        <%= content_tag :div, id: dom_id(queue) do %>
          <div class="queuers-card-bg" <% if index.even? %>
              style="background-color: #eeeeee;"
              <% end %>>
            <div class="queuers-card container">
              <div class="queuer-index"><p><%= index + 1 %></p>
              </div>
              <div class="queuers-card-name">
                <p class="email"><%= queue.user.email %></p>
                <p class="reservation-name"><%= queue.reservation_name %></p>
              </div>
              <div class="queuers-card-size">
                <% if queue.size === 1 %>
                  <p><span class="queuers-card-size-number"><%= queue.size %></span><span> Guest</p>
                <% else %>
                  <p><span class="queuers-card-size-number"><%= queue.size %></span> Guests</p>
                  <% end %>
              </div>


              <div class="queuers-card-action">
                <%= button_to notify_queuer_path(queue), method: :post, class: "no-btn-style" do %>
                  <div class="btn-action shadow queuing">
                      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 512 512"><path d="M464 64H48C21.49 64 0 85.49 0 112v288c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V112c0-26.51-21.49-48-48-48zm0 48v40.805c-22.422 18.259-58.168 46.651-134.587 106.49-16.841 13.247-50.201 45.072-73.413 44.701-23.208.375-56.579-31.459-73.413-44.701C106.18 199.465 70.425 171.067 48 152.805V112h416zM48 400V214.398c22.914 18.251 55.409 43.862 104.938 82.646 21.857 17.205 60.134 55.186 103.062 54.955 42.717.231 80.509-37.199 103.053-54.947 49.528-38.783 82.032-64.401 104.947-82.653V400H48z"/></svg>
                      <p>Notify</p>
                  </div>
                <% end %>
                <% Queuer::STATUS.each do |status| %>
                  <%= button_to change_status_queuer_path(queue, status: status), method: :patch, class: "no-btn-style" do %>
                  <% if status === "dining" %>
                    <div class="btn-action shadow dining">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><title>romantic-restaurant</title><g stroke-linecap="round" stroke-linejoin="round" stroke-width="2" fill="none" stroke="#212121"><line x1="8" y1="20" x2="24" y2="20"></line><line x1="16" y1="31" x2="16" y2="20"></line><line x1="31" y1="18" x2="31" y2="31"></line><polyline points="31 25 23 25 23 31"></polyline><line x1="1" y1="18" x2="1" y2="31"></line><polyline points="1 25 9 25 9 31"></polyline><path d="M21.881,2.157A3.74,3.74,0,0,0,16,2.768a3.741,3.741,0,0,0-5.882-.611,4.051,4.051,0,0,0,0,5.589L16,13.834l5.883-6.088A4.049,4.049,0,0,0,21.881,2.157Z" stroke="#212121"></path></g></svg>
                      <p>Dining</p>
                    </div>
                  <% end %>
                  <% end %>
                <% end %>
                  <%= button_to remove_queuer_queuer_path(queue),method: :delete, class: "no-btn-style" do %>
                  <div class="btn-action shadow remove">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>exit_to_app</title><g fill="none"><path d="M10.09 15.59L11.5 17l5-5-5-5-1.41 1.41L12.67 11H3v2h9.67l-2.58 2.59zM19 3H5a2 2 0 0 0-2 2v4h2V5h14v14H5v-4H3v4a2 2 0 0 0 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2z" fill="#212121"></path></g></svg>
                  <p>Remove</p></div>
                  <% end %>
              </div>
            </div>
          </div>

        <% end %>
      <% end %>
      <% end %>
      </div>
    </div>
    </div>

    <!-- Active Diners -->
    <div class="container p-2">
        <!-- Active Queue -->
        <div class="queuers-tableheaders">
          <h2>Dining</h2>
          <h3><%= @diners %> tables (<%= @number_of_diners %> guests)</h3>
        </div>
    </div>

    <div>
      <% @dining_queuers.each_with_index do | queue, index | %>
      <% if queue.status == "dining" %>
        <%= content_tag :div, id: dom_id(queue) do %>
          <div class="queuers-card-bg dining" <% if index.even? %>
              style="background-color: #eeeeee;"
              <% end %>>
            <div class="queuers-card container">
              <div class="queuer-index dining"><p><%= index + 1 %></p>
              </div>
              <div class="queuers-card-name">
                <p class="email"><%= queue.user.email %></p>
                <p class="reservation-name"><%= queue.reservation_name %></p>
              </div>
              <div class="queuers-card-size">
                <% if queue.size === 1 %>
                  <p><span class="queuers-card-size-number"><%= queue.size %></span><span> Guest</p>
                <% else %>
                  <p><span class="queuers-card-size-number"><%= queue.size %></span> Guests</p>
                  <% end %>
              </div>

              <div class="queuers-card-action">
                <% Queuer::STATUS.each do |status| %>
                  <%= button_to change_status_queuer_path(queue, status: status), method: :patch, class: "no-btn-style" do %>
                  <% if status === "dining" %>
                  <% elsif status === "completed" %>
                    <div class="btn-action shadow completed">
                      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24"><title>person_remove_alt_1</title><g fill="none"><path d="M14 8c0-2.21-1.79-4-4-4S6 5.79 6 8s1.79 4 4 4 4-1.79 4-4zm3 2v2h6v-2h-6zM2 18v2h16v-2c0-2.66-5.33-4-8-4s-8 1.34-8 4z" fill="#212121"></path></g></svg>
                      <p>Finished</p>
                    </div>
                  <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <% end %>
      </div>
    </div>
  </div>

app/views/queuers/_form.html.erb
<%= simple_form_for [ restaurant, queuer ] do |f| %>
  <%= f.input :reservation_name, label: false, placeholder: "Enter your name" %>
    <%= f.input :size, label: false, placeholder: "How many are you in your party?" %>
    <div class="modal-footer ">
    <%= f.submit "Join the queue" , class: "btn btn-primary" %>
    </div>
<% end %>

app/views/queuers/_history.html.erb
     <!-- Queue History -->
<div class="container p-2">
  <!-- Active Queue -->
  <div class="queuers-tableheaders">
    <h2>History</h2>
    <h3><%= @total_queuers.size %> guests</h3>
  </div>
</div>
<div>
  <% @total_queuers.each_with_index do | queue, index | %>
    <% if queue.status == "completed" %>
      <%= content_tag :div, id: dom_id(queue) do %>
        <div class="queuers-card-bg completed" <% if index.even? %>
              style="background-color: #eeeeee;"
              <% end %>>
          <div class="queuers-card container">
            <div class="queuer-index completed">
              <p><%= index + 1 %></p>
            </div>
            <div class="queuers-card-name">
              <p class="email"><%= queue.user.email %></p>
              <p class="reservation-name"><%= queue.reservation_name %></p>
            </div>
            <div class="queuers-card-size">
              <% if queue.size === 1 %>
                <p><span class="queuers-card-size-number"><%= queue.size %></span><span> Guest</p>
                <% else %>
                  <p><span class="queuers-card-size-number"><%= queue.size %></span> Guests</p>
                <% end %>
              </div>
              <div class="queuers-card-action">
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/queuers/index.html.erb
<%= render "active" %>

<%= render "history" %>


<script>

  // Adding styling after generating bookings list
  var queueStatus = document.querySelectorAll('.status')
  queueStatus.forEach(status => {
    if (status.innerHTML === 'queuing') {
      status.classList.add('queuing');
      status.innerHTML = '<div class="mt-3" ><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24"><title>time-machine</title><g fill="#212121"><path d="M12,0A12.013,12.013,0,0,0,0,12a1,1,0,0,0,2,0,10.023,10.023,0,1,1,4.379,8.26L8.184,18a.5.5,0,0,0-.349-.809l-6.672-.568a.5.5,0,0,0-.519.65l2.042,6.377a.5.5,0,0,0,.385.339.476.476,0,0,0,.091.009.5.5,0,0,0,.391-.189l1.578-1.98A12,12,0,1,0,12,0Z" fill="#212121"></path><path d="M12,4a1,1,0,0,0-1,1v7a1,1,0,0,0,1,1h7a1,1,0,0,0,0-2H13V5A1,1,0,0,0,12,4Z"></path></g></svg><p>Queuing</p></div>';
    } else if (status.innerHTML === 'completed') {
      status.classList.add('completed');
      status.innerHTML = '<div class="mt-3" ><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24"><title>person_remove_alt_1</title><g fill="none"><path d="M14 8c0-2.21-1.79-4-4-4S6 5.79 6 8s1.79 4 4 4 4-1.79 4-4zm3 2v2h6v-2h-6zM2 18v2h16v-2c0-2.66-5.33-4-8-4s-8 1.34-8 4z" fill="#212121"></path></g></svg><p>Finished</p></div>';

      } else if (status.innerHTML === 'dining') {
        status.classList.add('dining');
        status.innerHTML = '<div class="mt-3" ><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><title>romantic-restaurant</title><g stroke-linecap="round" stroke-linejoin="round" stroke-width="2" fill="none" stroke="#212121"><line x1="8" y1="20" x2="24" y2="20"></line><line x1="16" y1="31" x2="16" y2="20"></line><line x1="31" y1="18" x2="31" y2="31"></line><polyline points="31 25 23 25 23 31"></polyline><line x1="1" y1="18" x2="1" y2="31"></line><polyline points="1 25 9 25 9 31"></polyline><path d="M21.881,2.157A3.74,3.74,0,0,0,16,2.768a3.741,3.741,0,0,0-5.882-.611,4.051,4.051,0,0,0,0,5.589L16,13.834l5.883-6.088A4.049,4.049,0,0,0,21.881,2.157Z" stroke="#212121"></path></g></svg><p>Dining</p></div>';
      }
  });

</script>

app/views/queuers/new.html.erb
<div class="container">
  <h1 class="my-5 text-center">Join a Queue</h1>
  <div class="row justify-content-center my-5">
    <div class="col-6">
      <%= simple_form_for [@restaurant, @queuer] do |f| %>
        <%= f.input :reservation_name, label: false, input_html: { value: @username }  %>
        <%= f.input :size, label: false, placeholder: "How many are you in your party?" %>
        <%= f.input :size, label: "Where should we send your queue notification?" %>
        <%= f.submit "Join the queue" , class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/queuers/show.html.erb
<% content_for :meta_title, "Your #{DEFAULT_META["meta_title"]} ticket for #{@restaurant.name}" %>

<div class="col-lg-0"></div>
<div class="row">
<div class="col-lg-6">
<%# restaurant photo and name banner %>
  <div class="restaurant-name-container shadow" <% if @restaurant.photos.attached? %>
                  style="height: 100px; background-image: url('<%= cl_image_path @restaurant.photos.first.key %>')"
                <% else %>
                  style="height: 100px; opacity: 50%; background-image: url('https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80')"
                <% end %>>
    <div class="restaurant-title-container">
      <h1><%= @restaurant.name  %></h1>
    </div>
  </div>
<%# Queuer Details %>
  <div class="title-container ">
    <div>
      <h3>RESERVATION NAME:</h3>
      <h1><%= @queuer.reservation_name.capitalize %></h1>
    </div>
<%# leacve queue %>
    <div class="align-self-center">
      <%= button_to "Leave the Queue",
                queuer_path(@queuer),
                method: :delete,
                class: "leave-btn",
                data: { confirm: "Are you sure?" } %>
    </div>
  </div>
<%# Auto updated queue information  %>
  <div data-controller="queue-time" id="queuer-<%= @queuer.id %>">
    <div class="info-card-container">

      <div class="info-card ">
        <div class="icon-container">
          <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24"><title>groups</title><g fill="none"><path d="M12 12.75c1.63 0 3.07.39 4.24.9 1.08.48 1.76 1.56 1.76 2.73V18H6v-1.61c0-1.18.68-2.26 1.76-2.73 1.17-.52 2.61-.91 4.24-.91zM4 13c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm1.13 1.1c-.37-.06-.74-.1-1.13-.1-.99 0-1.93.21-2.78.58A2.01 2.01 0 0 0 0 16.43V18h4.5v-1.61c0-.83.23-1.61.63-2.29zM20 13c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm4 3.43c0-.81-.48-1.53-1.22-1.85A6.95 6.95 0 0 0 20 14c-.39 0-.76.04-1.13.1.4.68.63 1.46.63 2.29V18H24v-1.57zM12 6c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3z" fill="#212121"></path></g></svg>
          <p class="card-restaurant-icon-number" data-queue-time-target="people"><%= @number_of_people %></p>
          <p class="small">People Ahead</p>
        </div>
      </div>

      <div class="info-card ">
        <div class="icon-container">
          <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24"><title>emoji_people</title><g fill="none"><path d="M12 6a2 2 0 1 0 0-4 2 2 0 0 0 0 4z" fill="#212121"></path><path d="M15.89 8.11C15.5 7.72 14.83 7 13.53 7h-2.54C8.24 6.99 6 4.75 6 2H4c0 3.16 2.11 5.84 5 6.71V22h2v-6h2v6h2V10.05L18.95 14l1.41-1.41-4.47-4.48z" fill="#212121"></path></g></svg>
          <p class="card-restaurant-icon-number" data-queue-time-target="position"><%= @position %></p>
          <p class="small" >Place</p>
        </div>
      </div>

      <div class="info-card " id="queuer">
        <div class="icon-container">
          <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24"><title>access_time</title><g fill="none"><path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm.5-13H11v6l5.25 3.15.75-1.23-4.5-2.67V7z" fill="#212121"></path></g></svg>
          <p class="card-restaurant-icon-number" data-queue-time-target="time"><%= @time %></p>
          <p class="small" >Wait Time</p>
        </div>
      </div>

    </div>
    <%# Estimated wait time %>
    <div class="title-container">
      <div class="dining-time-container">
        <div class="dining-card">
        <h3>Estimated Dining Time:</h3>
          <div class="d-flex justify-content-evenly dining-info">
            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24"><title>romantic-restaurant</title><g fill="#212121"><path d="M16.621,5.121,12,9.743,7.379,5.121A3,3,0,0,1,11.621.879L12,1.257l.379-.378a3,3,0,1,1,4.242,4.242Z"></path><path d="M17,16a1,1,0,0,0,0-2H7a1,1,0,0,0,0,2h4v8h2V16Z" fill="#212121"></path><path d="M22,12v6H17a1,1,0,0,0-1,1v5h2V20h4v4h2V12Z" fill="#212121"></path><path d="M7,18H2V12H0V24H2V20H6v4H8V19A1,1,0,0,0,7,18Z" fill="#212121"></path></g></svg>
            <h1 data-queue-time-target="dine"><%= @dine_time %></h1>
          </div>
        </div>
      </div>
    </div>
    </div>
</div>

  <div class="map-container col-lg-6">
    <div class="map-style" style="width: 100%; height: 550px; overflow:hidden; border-radius: 0px 20px 0px 0px;"
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>