config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user, ->(user) { user.owner? } do
    get 'owner', to: 'owner#dashboard'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :restaurants do
    resources :queuers, only: [ :new, :create, :edit, :update ]

    resources :reviews, only: [ :new, :create, :index ]
  end

  resources :queuers do
    resources :queuers, only: [ :show, :index, :destroy, :update ]
    member do
      patch :change_status
      delete :remove_queuer
      delete :quick_remove
      post :notify
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<p>RetsuQueue 2022</p>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_modal.html.erb
<!-- Modal -->
<div class="new-queuer-modal modal fade" id="<%= modal_id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-info">
        <h5 class="modal-title" id="exampleModalLabel">Join the Queue</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="row pb-4">
          <div class="col stat-info">
            <p>Est. waiting Time</p>
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24"><title>access_time</title><g fill="none"><path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm.5-13H11v6l5.25 3.15.75-1.23-4.5-2.67V7z" fill="#212121"></path></g></svg>
              <%= restaurant.total_wait_time %> mins
            </div>
          </div>
          <div class="col stat-info">
            <p>In front of you </p>
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24"><title>emoji_people</title><g fill="none"><path d="M12 6a2 2 0 1 0 0-4 2 2 0 0 0 0 4z" fill="#212121"></path><path d="M15.89 8.11C15.5 7.72 14.83 7 13.53 7h-2.54C8.24 6.99 6 4.75 6 2H4c0 3.16 2.11 5.84 5 6.71V22h2v-6h2v6h2V10.05L18.95 14l1.41-1.41-4.47-4.48z" fill="#212121"></path></g></svg>
              <%= restaurant.line_size %> group(s)
            </div>
          </div>
        </div>
        <%= render "queuers/form", restaurant: restaurant, queuer: @queuer %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-main sticky-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "navbar-icon.png" %>
  <% end %>

  <div class="navbar-right">
    <% if user_signed_in? %>
    <div text-align="center">
      <% if @Aqueuer.present? && @Aqueuer.restaurant.present? %>
          <%= link_to "Current Queue", queuers_path(@user), class: "user-queue queued"%>
      <% else %>
        <div class="user-queue notqueued" disabled>
          You have not queued yet
        </div>
      <% end %>
    </div>

    <div class="dropdown">
      <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false" style="background: white;">
      <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24"><title>menu</title><g fill="none"><path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z" fill="#212121"></path></g></svg>    </button>
      <ul class="dropdown-menu dropdown-menu-end nav-img" aria-labelledby="dropdownMenuButton1">
        <h3>ようこそ！</h3>
        <li><p class="dropdown-item menu-username"><%= current_user.email %></p></li>
        <li><p class="dropdown-item text-decoration-none" ><%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "text-decoration-none"%></p></li>
      </ul>
    </div>
  <% else %>
    <div>
        <%= link_to "Sign In", new_user_session_path, class: "button signin" %>
        <%= link_to "Sign Up",  new_user_registration_path, class: "button signup" %>
    </div>
  <% end %>
  </div>
</div>

app/views/shared/_owner_navbar.html.erb
<div class="<%= 'navbar navbar-expand navbar-light navbar-owner' %>">

  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "RetsuQ_logo_large.png" %>
  <% end %>

  <div class="navbar-right">
    <div class="form-check form-switch queue-status">
    <% if current_user.restaurant.status == 'open' %>
      <%= simple_form_for current_user.restaurant do |f| %>
        <%= f.input :status, as: :boolean, label: false, input_html: { class: "toggle", value: 'closed', onchange: "this.form.submit();"} %>
        <%#= f.submit wrapper: :custom_boolean_switch, class: "form-check-input" %>
      <% end %>
    <% else %>
      <%= simple_form_for current_user.restaurant do |f| %>
        <%= f.input :status, as: :boolean, label: false, input_html: { class: "toggle", value: 'open', onchange: "this.form.submit();"} %>
        <%#= f.submit wrapper: :custom_boolean_switch, class: "form-check-input" %>
      <% end %>
    <% end %>
    </div>

    <div class="add-queuer">
      <%= link_to new_restaurant_queuer_path(current_user.restaurant.id) do %>
        <i class="fas fa-plus"></i>
      <% end %>
    </div>

    <div class="dropdown">
      <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
      <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24"><title>menu</title><g fill="none"><path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z" fill="#212121"></path></g></svg></button>

      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
        <li><p class="dropdown-item menu-username"><%= current_user.email %></p></li>
        <li><p class="dropdown-item text-decoration-none" ><%= link_to "Dashboard", owner_path, class: "text-decoration-none" if current_user.owner? %></p></li>
        <li><p class="dropdown-item text-decoration-none" ><%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "text-decoration-none"%></p></li>
      </ul>
    </div>
    </div>
    </div>