config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user, ->(user) { user.owner? } do
    get 'owner', to: 'owner#dashboard'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :restaurants do
    resources :queuers, only: [ :new, :create, :edit, :update ]

    resources :reviews, only: [ :new, :create, :index ]
  end

  resources :queuers do
    resources :queuers, only: [ :show, :index, :destroy, :update ]
    member do
      patch :change_status
      delete :remove_queuer
      delete :quick_remove
      post :notify
    end
  end
end

app/views/pages/_info_window.html.erb
    <div>
      <a href="<%=restaurant_path(restaurant)%>">
        <div class="card-restaurant-thumbnail map"
              <% if restaurant.photos.attached? %>
                style="height: 100px; margin-top: 2em; background-image: url('<%= cl_image_path restaurant.photos.first.key  %>')"
              <% else %>
                style="height: 100px; margin-top: 2em; background-image: url('https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80')"
              <% end %>>
        </div>
        </a>
        <div class="card-restaurant-content px-1 pb-0" style="box-shadow: none;">

          <div class="card-restaurant-details">
          <span class="card-restaurant-category"><%= restaurant.category %></span>
            <div class="card-restaurant-details-top">
              <span class="card-restaurant-title"><%= restaurant.name %></span>
              <span class="card-restaurant-budget"><%= restaurant.price_range %></span>
            </div>

          </div>
          <div data-controller="time" id="restaurant-<%= restaurant.id %>">
            <div class="card-restaurant-actions">
              <div class="card-restaurant-icon-small">
                <span class="card-restaurant-icon-number" data-time-target="customers"><%= restaurant.queuers.where(status: "queuing").count %></span>
                <span class="card-restaurant-icon-subtitle">waiting</span>
              </div>
              <div class="card-restaurant-icon-small">
                <span class="card-restaurant-icon-number" data-time-target="wait"><%= restaurant.total_wait_time %></span>
                <span class="card-restaurant-icon-subtitle">mins</span>
              </div>

              <!-- Join Queue Button -->
              <%= link_to 'Join Queue', new_restaurant_queuer_path(restaurant), class: "card-restaurant-icon-big" %>
            </div>
          </div>
        </div>
      </div>

app/views/pages/_near_restaurants.html.erb
<%= restaurants.each do | restaurant | %>
<div class="card-base card-restaurant"  data-controller="restaurant-card">
<a href="<%=restaurant_path(restaurant)%>">
  <div class="card-restaurant-thumbnail"
        <% if restaurant.photos.attached? %>
          style="height: 100px; background-image: url('<%= cl_image_path restaurant.photos.first.key %>')"
        <% else %>
          style="height: 100px; background-image: url('https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80')"
        <% end %>>
    <div class="overlay" data-restaurant-card-target="overlay">
      <div class="card-restaurant-status" data-restaurant-card-target="status"><%= restaurant.current_status %></div>
    </div>
    </div>
  </a>
  <div class="card-restaurant-content">

    <div class="card-restaurant-details">
    <span class="card-restaurant-category"><%= restaurant.category %></span>
      <div class="card-restaurant-details-top">
        <span class="card-restaurant-title"><%= restaurant.name %></span>
        <span class="card-restaurant-budget"><%= restaurant.price_range %></span>
      </div>

    </div>
<div data-controller="time" id="restaurant-<%= restaurant.id %>">
    <div class="card-restaurant-actions">
      <div class="card-restaurant-icon-small" data-restaurant-card-target="customers">
        <span class="card-restaurant-icon-number" data-time-target="customers"><%= restaurant.queuers.where(status: "queuing").count %></span>
        <span class="card-restaurant-icon-subtitle">waiting</span>
      </div>
      <div class="card-restaurant-icon-small" data-restaurant-card-target="wait">
        <span class="card-restaurant-icon-number" data-time-target="wait"><%= restaurant.total_wait_time %></span>
        <span class="card-restaurant-icon-subtitle">mins</span>
      </div>

      <!-- Join Queue Button -->
      <%= link_to 'Join Queue', new_restaurant_queuer_path(restaurant), class: "card-restaurant-icon-big", data: { restaurant_card_target: "join" } %>
    </div>
    </div>
  </div>
</div>

<% end %>

app/views/pages/_restaurant_card.html.erb
<div class="card-base card-restaurant"  data-controller="restaurant-card">
<a href="<%=restaurant_path(restaurant)%>">
  <div class="card-restaurant-thumbnail"
        <% if restaurant.photos.attached? %>
          style="height: 100px; background-image: url('<%= cl_image_path restaurant.photos.first.key %>')"
        <% else %>
          style="height: 100px; background-image: url('https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80')"
        <% end %>>
    <div class="overlay" data-restaurant-card-target="overlay">
      <div class="card-restaurant-status" data-restaurant-card-target="status"><%= restaurant.current_status %></div>
    </div>
    </div>
  </a>
  <div class="card-restaurant-content">

    <div class="card-restaurant-details">
    <span class="card-restaurant-category"><%= restaurant.category %></span>
      <div class="card-restaurant-details-top">
        <span class="card-restaurant-title"><%= restaurant.name %></span>
        <span class="card-restaurant-budget"><%= restaurant.price_range %></span>
      </div>

    </div>
<div id="restaurant-<%= restaurant.id %>">
    <div class="card-restaurant-actions">
      <div class="card-restaurant-icon-small" data-restaurant-card-target="customers">
        <span class="card-restaurant-icon-number"><%= restaurant.queuers.where(status: "queuing").count %></span>
        <span class="card-restaurant-icon-subtitle">waiting</span>
      </div>
      <div class="card-restaurant-icon-small card-restaurant-icon-small-right" data-restaurant-card-target="wait">
        <span class="card-restaurant-icon-number"><%= restaurant.total_wait_time %></span>
        <span class="card-restaurant-icon-subtitle">mins</span>
      </div>
      <!-- Button trigger modal -->
        <button class="card-restaurant-icon-big" type="button" id="home-page-join-btn" data-restaurant_card_target="join" data-bs-toggle="modal" data-bs-target="#restaurant-modal-<%= restaurant.id %>" <% restaurant.current_status == 'Closed' ? 'disabled' : '' %>>
          Join Queue
        </button>
    </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<section>
  <h3>Search on Map</h3>

    <div style="width: 100%; height: 550px; overflow:hidden; border-radius: 10px ;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

</section>

<!-- >
<section data-controller="nearrestaurants">
  <h3>Restaurants near you</h3>
  <label for="restaurantRange" class="form-label">Max. distance from your location:</label>
  <input type="range" class="form-range" min="0" max="1000" step="5" id="restaurantRange" data-action="change->nearrestaurants#getRestaurants">

  <div class="restaurants-wrapper" data-nearrestaurants-target="nearyou">
  </div>
</section>
-->

<section>
  <h3>Restaurants in Tokyo</h3>
  <!-- Flexbox wrapper for restaurant cards -->
  <div class="restaurants-wrapper">
    <% @restaurants.each do |restaurant| %>  <!--Start iteration -->
      <%= render "restaurant_card", restaurant: restaurant %>
      <%= render "shared/modal", restaurant: restaurant, modal_id: "restaurant-modal-#{restaurant.id}" %>
    <% end %>
  </div>

</section>