config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user, ->(user) { user.owner? } do
    get 'owner', to: 'owner#dashboard'
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :restaurants do
    resources :queuers, only: [ :new, :create, :edit, :update ]

    resources :reviews, only: [ :new, :create, :index ]
  end

  resources :queuers do
    resources :queuers, only: [ :show, :index, :destroy, :update ]
    member do
      patch :change_status
      delete :remove_queuer
      delete :quick_remove
      post :notify
    end
  end
end

app/controllers/owner_controller.rb
class OwnerController < ApplicationController
  def dashboard
    @restaurant = current_user.restaurant
    @queuers = Queuer.where(restaurant_id: @restaurant, status: "queuing")
    @queuers = @queuers.order(created_at: :asc)
    @next_queuer = Queuer.where(restaurant_id: current_user.restaurant, status: "queuing")
    @next_queuer = @next_queuer.order(created_at: :asc).first
    if @next_queuer.nil?
      # redirect_to owner_path, notice: "No queuers in queue"
      root_path
    end
  end

  def queuers
    @queurs = Queuer.all
  end

  def call_next_queuer
    @next_queuer = @next_queuer = Queuer.where(restaurant_id: current_user.restaurant, status: "queuing").first
    if @next_queuer.nil?
      redirect_to owner_path, notice: "No queuers in queue"
    else
      @next_queuer.update(status: "dining")
      @next_queuer.save
      QueuerMailer.with(queuer: @next_queuer).next_queuer(@next_queuer).deliver_later
      redirect_to owner_path, notice: "Next queuer called"
    end
  end
end

app/views/owner/dashboard.html.erb
<style>
 .dashboard-owner-options > img {
  width: 50px;
  height: 50px;
 }
</style>

<div class="container pt-5 dashboard-wrapper">
  <div class="row">
    <div class="col-8 dashboard-owner">
      <h3 class="pt-2">Dashboard</h3>
      <div class="dashboard-owner-options-grid">
        <div class="dashboard-owner-options-item"><%= image_tag "icons-queue-management.svg" %> <%= link_to "Queue Management", queuers_path %></div>
        <div class="dashboard-owner-options-item"><%= image_tag "icons-analytics.svg" %> Queue Analytics</div>
        <div class="dashboard-owner-options-item"><%= image_tag "icons-discounts.svg" %> Rewards & Discounts</div>
        <div class="dashboard-owner-options-item"><%= image_tag "icons-restaurant-profile.svg" %>  <%= link_to "Restaurant Details", edit_restaurant_path(@restaurant) %> </div>
        <div class="dashboard-owner-options-item"><%= image_tag "icons-queue-history.svg" %>  Queue History</div>
        <div class="dashboard-owner-options-item"><%= image_tag "icons-ratings.svg" %> <%= link_to "Reviews & Ratings", restaurant_reviews_path(@restaurant) %></div>
      </div>
    </div>
    <!-- Live Queue-->
    <div class="col-4 live-queue">
      <div class="show-next-queuer">
        <% if @next_queuer.present? %>
          <p>Next Queuer: <%= @next_queuer.reservation_name %></p>
          <p><%= @next_queuer.size %> Guests in Queue</p>
        <% else %>
          <p>No queuers in queue</p>
        <% end %>

        <div class="next-queuer-actions">
          <% if @next_queuer.present? %>
            <%= button_to notify_queuer_path(@next_queuer), class: "no-btn-style" do %>
            <div class="btn-action shadow queuing">
              <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 512 512"><path d="M464 64H48C21.49 64 0 85.49 0 112v288c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V112c0-26.51-21.49-48-48-48zm0 48v40.805c-22.422 18.259-58.168 46.651-134.587 106.49-16.841 13.247-50.201 45.072-73.413 44.701-23.208.375-56.579-31.459-73.413-44.701C106.18 199.465 70.425 171.067 48 152.805V112h416zM48 400V214.398c22.914 18.251 55.409 43.862 104.938 82.646 21.857 17.205 60.134 55.186 103.062 54.955 42.717.231 80.509-37.199 103.053-54.947 49.528-38.783 82.032-64.401 104.947-82.653V400H48z"/></svg>
              <p>Notify</p>
            </div>
            <% end %>
            <%= button_to remove_queuer_queuer_path(@next_queuer), method: :delete, class: "no-btn-style", :confirm => "Are you sure?" do %>
            <div class="btn-action shadow dining">
              <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><title>romantic-restaurant</title><g stroke-linecap="round" stroke-linejoin="round" stroke-width="2" fill="none" stroke="#212121"><line x1="8" y1="20" x2="24" y2="20"></line><line x1="16" y1="31" x2="16" y2="20"></line><line x1="31" y1="18" x2="31" y2="31"></line><polyline points="31 25 23 25 23 31"></polyline><line x1="1" y1="18" x2="1" y2="31"></line><polyline points="1 25 9 25 9 31"></polyline><path d="M21.881,2.157A3.74,3.74,0,0,0,16,2.768a3.741,3.741,0,0,0-5.882-.611,4.051,4.051,0,0,0,0,5.589L16,13.834l5.883-6.088A4.049,4.049,0,0,0,21.881,2.157Z" stroke="#212121"></path></g></svg><p>Dining</p>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="container analytics">
    <h3 class="pt-4">Queue Analytics</h3>
    <div class="chart" >
      <%= line_chart Queuer.group_by_day(:created_at).count, width: "100%", height: "240px", colors: ["pink"], empty: "No data", download: true %>
    </div>
</div>